---
data:
  channel: 'hgg_statonly'
  model: 'STXStoSMEFTExpandedLinearStatOnly3D'
  type: 'observed'
  attribute: 'nominal'
  POIs:
    lchgXE3: 
      bounds: [-35, 10]
    lchwXE2:
      bounds: [-5,5]
    lctgreXE1:
      bounds: [-15, 10]
  interpolator:
    mode: "RBF"
    eps: 0.5
  splitting: "grid"
  fraction: 0.25
  subtractbest: False
...
